# Generated by Django 5.0.7 on 2024-07-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_quastion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='slug',
        ),
    ]
