# Generated by Django 5.0.7 on 2024-07-16 23:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_answer_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quastion',
            new_name='Question',
        ),
    ]
