# Generated by Django 5.0.7 on 2024-07-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_quastion_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quastion',
            new_name='question',
        ),
    ]
