# Generated by Django 5.0.7 on 2024-07-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_quastion_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
    ]
